# Generated by Django 5.2.1 on 2025-05-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_attendace"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendace",
            name="timestamp",
            field=models.DateTimeField(),
        ),
    ]
